name: Check Commit Messages
description: This action will peform checks on your commits.
author: BetaTH13

inputs:
  keyword:
    description: "Keyword to search for in commit messages"
    required: true
  require-all:
    description: "All commit messages must contain the keyword"
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Ensure this is a PR
      shell: bash
      run: |
        if [[ "${{ github.event_name }}" != "pull_request" ]]; then
          echo "❌ This action only supports pull_request events."
          exit 1
        fi

    - name: Fetch PR commit
      shell: bash
      run: |
        git fetch --prune --unshallow || true

    - name: Check commit message for keyword
      shell: bash
      run: |
        bash "./scripts/check_commits.sh" \
          "${{ inputs.keyword }}" \
          "${{ inputs.require-all }}" \
          "${{ github.event.pull_request.base.sha }}" \
          "${{ github.event.pull_request.head.sha }}"
