name: check-commit-messages-by-keyword
description: Checks commit messages in a pull request for a specific keyword.
author: BetaTH13
branding:
  icon: 'check'
  color: 'green'

inputs:
  keyword:
    description: "Keyword to search for in commit messages"
    required: true
  require-all:
    description: "All commit messages must contain the keyword"
    required: false
    default: 'false'
  commit-limit:
    description: "Maximum number of commits permitted in a pull request."
    required: false

runs:
  using: "composite"
  steps:
    - name: Ensure this is a PR
      id: pr-check
      shell: bash
      run: |
        if [[ "${{ github.event_name }}" != "pull_request" ]]; then
          echo "❌ This action only supports pull_request events."
          exit 1
        fi

    - name: Fetch PR commit
      id: fetch-commits
      shell: bash
      run: |
        git fetch --prune || true

    - name: Check commit message for keyword
      id: check-commit-keyword
      shell: bash
      run: |
        bash "${GITHUB_ACTION_PATH}/scripts/check-commits-keyword.sh" \
          "${{ inputs.keyword }}" \
          "${{ inputs.require-all }}" \
          "${{ github.event.pull_request.base.sha }}" \
          "${{ github.event.pull_request.head.sha }}"

    - name: Check amount of commits
      id: check-commit-amount
      shell: bash
      run: |
        COMMIT_LIMIT=${{ inputs.commit-limit }}
        TOTAL_COMMITS=${{ steps.check-commit-keyword.outputs.total-commits }}

        if [[ $TOTAL_COMMITS > COMMIT_LIMIT ]]
          echo "❌ amount of commits $TOTAL_COMMITS has exceeded the limit of $COMMIT_LIMIT" 
          exit 1
        fi

