name: CI check commit

on: pull_request
jobs:
  fails-when-no-match:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Run action with impossible keyword (should fail)
        id: run
        continue-on-error: true
        uses: ./
        with:
          keyword: "$RANDOM-$(date +%s)"

      - name: Assert it failed as expected
        if: steps.run.outcome == 'success'
        run: |
          echo "❌ Expected failure did not happen"
          exit 1
          
  fails-when-keyword-too-long:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run action with too-long keyword (should fail)
        id: run-long
        continue-on-error: true
        uses: ./
        with:
          keyword: |
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

      - name: Assert keyword length check triggered
        if: steps.run-long.outcome == 'success'
        run: |
          echo "❌ Expected failure for long keyword did not happen"
          exit 1
