name: check commit messages

on: 
  pull_request:
    branches: [ master ]

jobs: 
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run commit message check
        uses: BetaTH13/check-commit@1.0.0
        with:
          keyword: "JIRA-"
          require-all: true